# Generated by Django 3.0 on 2019-12-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
            ('Revitalize', '0001_initial'),
            ]

    operations = [
            migrations.CreateModel(
                    name='AnonymizedIndicator',
                    fields=[
                            ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                            ('type', models.CharField(
                                choices=[('?', 'Unknown'), ('I', 'Integer'), ('F', 'Decimal'), ('B', 'Boolean'),
                                         ('C', 'Category')], default='?', help_text='This should be a data type.',
                                max_length=40)),
                            ('specification', models.TextField(help_text='This should be a JSON.')),
                            ('analysis', models.TextField(help_text='This should be a JSON.')),
                            ],
                    options={
                            'abstract': False,
                            },
                    ),
            migrations.CreateModel(
                    name='Client',
                    fields=[
                            ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                            ('username',
                             models.EmailField(help_text='The email address a user will log in with.', max_length=254,
                                               unique=True)),
                            ('first_name', models.CharField(max_length=40)),
                            ('middle_name', models.CharField(blank=True, max_length=40)),
                            ('last_name', models.CharField(max_length=40)),
                            ('birth_date', models.DateField()),
                            ('creation_time', models.DateTimeField(auto_now_add=True)),
                            ('points', models.BigIntegerField(verbose_name='Health Currency')),
                            ('password_flag',
                             models.BooleanField(default=True, help_text='True if the password needs to be reset.',
                                                 verbose_name='Password Reset Flag')),
                            ],
                    ),
            migrations.CreateModel(
                    name='Cohort',
                    fields=[
                            ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                            ('name', models.CharField(max_length=40, unique=True)),
                            ('clients', models.ManyToManyField(db_table='cohort_membership', to='Revitalize.Client')),
                            ],
                    ),
            migrations.CreateModel(
                    name='CohortDataPoint',
                    fields=[
                            ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                            ('creation_time', models.DateTimeField(auto_now_add=True)),
                            ('time', models.DateTimeField()),
                            ('value', models.TextField(help_text='This should be a JSON.')),
                            ('a_client_id', models.IntegerField()),
                            ('a_indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                              to='Revitalize.AnonymizedIndicator')),
                            ('cohort',
                             models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revitalize.Cohort')),
                            ],
                    options={
                            'abstract': False,
                            },
                    ),
            migrations.CreateModel(
                    name='DataPoint',
                    fields=[
                            ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                            ('creation_time', models.DateTimeField(auto_now_add=True)),
                            ('time', models.DateTimeField()),
                            ('value', models.TextField(help_text='This should be a JSON.')),
                            ('client',
                             models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revitalize.Client')),
                            ],
                    options={
                            'abstract': False,
                            },
                    ),
            migrations.CreateModel(
                    name='Form',
                    fields=[
                            ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                            ('name', models.CharField(max_length=40, unique=True)),
                            ('type', models.CharField(choices=[('?', 'Unknown'), ('S', 'Survey'), ('M', 'Medical Test'),
                                                               ('D', 'Dietary Journal Entry')], default='?',
                                                      max_length=40)),
                            ('display', models.TextField(help_text='This should be a JSON.')),
                            ('specification', models.TextField(help_text='This should be a JSON.')),
                            ('analysis', models.TextField(help_text='This should be a JSON.')),
                            ],
                    ),
            migrations.CreateModel(
                    name='Goal',
                    fields=[
                            ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                            ('creation_time', models.DateTimeField(auto_now_add=True)),
                            ('start', models.DateTimeField()),
                            ('target', models.TextField(help_text='This should be a JSON.')),
                            ('completed', models.BooleanField(default=False)),
                            ('client',
                             models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revitalize.Client')),
                            ],
                    ),
            migrations.CreateModel(
                    name='Indicator',
                    fields=[
                            ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                            ('type', models.CharField(
                                choices=[('?', 'Unknown'), ('I', 'Integer'), ('F', 'Decimal'), ('B', 'Boolean'),
                                         ('C', 'Category')], default='?', help_text='This should be a data type.',
                                max_length=40)),
                            ('specification', models.TextField(help_text='This should be a JSON.')),
                            ('analysis', models.TextField(help_text='This should be a JSON.')),
                            ('name', models.CharField(max_length=40, unique=True)),
                            ],
                    options={
                            'abstract': False,
                            },
                    ),
            migrations.CreateModel(
                    name='Submission',
                    fields=[
                            ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                            ('creation_time', models.DateField(auto_now_add=True)),
                            ('time', models.DateTimeField()),
                            ('values', models.TextField(help_text='This should be a JSON.')),
                            ('client',
                             models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Revitalize.Client')),
                            ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                       to='Revitalize.Form')),
                            ],
                    ),
            migrations.DeleteModel(
                    name='User',
                    ),
            migrations.AddField(
                    model_name='goal',
                    name='indicator',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to='Revitalize.Indicator'),
                    ),
            migrations.AddField(
                    model_name='datapoint',
                    name='indicator',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to='Revitalize.Indicator'),
                    ),
            migrations.AddField(
                    model_name='anonymizedindicator',
                    name='indicator',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to='Revitalize.Indicator'),
                    ),
            ]
